import pytest
from app.common.parsers.instruction_parser import InstructionParser

router_config_1 = [
        "!",
        "version 15.1",
        "no service timestamps log datetime msec",
        "no service timestamps debug datetime msec",
        "no service password-encryption",
        "!",
        "hostname Router",
        "!",
        "!",
        "!",
        "!",
        "!",
        "!",
        "!",
        "!",
        "ip cef",
        "no ipv6 cef",
        "!",
        "!",
        "!",
        "!",
        "license udi pid CISCO2911/K9 sn FTX15249Q72-",
        "!",
        "!",
        "!",
        "!",
        "!",
        "!",
        "!",
        "!",
        "!",
        "!",
        "!",
        "spanning-tree mode pvst",
        "!",
        "!",
        "!",
        "!",
        "!",
        "!",
        "interface GigabitEthernet0/0",
        "no ip address",
        "duplex auto",
        "speed auto",
        "!",
        "interface GigabitEthernet0/0.10",
        "encapsulation dot1Q 10",
        "ip address 100.0.0.1 255.255.255.0",
        "!",
        "interface GigabitEthernet0/0.20",
        "encapsulation dot1Q 20",
        "ip address 200.0.0.2 255.255.255.0",
        "!",
        "interface GigabitEthernet0/1",
        "no ip address",
        "duplex auto",
        "speed auto",
        "shutdown",
        "!",
        "interface GigabitEthernet0/2",
        "no ip address",
        "duplex auto",
        "speed auto",
        "shutdown",
        "!",
        "interface Vlan1",
        "no ip address",
        "shutdown",
        "!",
        "ip classless",
        "!",
        "ip flow-export version 9",
        "!",
        "!",
        "!",
        "!",
        "!",
        "!",
        "!",
        "line con 0",
        "!",
        "line aux 0",
        "!",
        "line vty 0 4",
        "login",
        "!",
        "!",
        "!",
        "end"
      ]
switch_config_1 = [
        "!",
        "version 15.0",
        "no service timestamps log datetime msec",
        "no service timestamps debug datetime msec",
        "no service password-encryption",
        "!",
        "hostname Switch",
        "!",
        "!",
        "!",
        "!",
        "!",
        "!",
        "spanning-tree mode pvst",
        "spanning-tree extend system-id",
        "!",
        "interface FastEthernet0/1",
        "!",
        "interface FastEthernet0/2",
        "!",
        "interface FastEthernet0/3",
        "!",
        "interface FastEthernet0/4",
        "!",
        "interface FastEthernet0/5",
        "!",
        "interface FastEthernet0/6",
        "!",
        "interface FastEthernet0/7",
        "!",
        "interface FastEthernet0/8",
        "!",
        "interface FastEthernet0/9",
        "!",
        "interface FastEthernet0/10",
        "!",
        "interface FastEthernet0/11",
        "!",
        "interface FastEthernet0/12",
        "!",
        "interface FastEthernet0/13",
        "!",
        "interface FastEthernet0/14",
        "!",
        "interface FastEthernet0/15",
        "!",
        "interface FastEthernet0/16",
        "!",
        "interface FastEthernet0/17",
        "!",
        "interface FastEthernet0/18",
        "!",
        "interface FastEthernet0/19",
        "!",
        "interface FastEthernet0/20",
        "!",
        "interface FastEthernet0/21",
        "!",
        "interface FastEthernet0/22",
        "!",
        "interface FastEthernet0/23",
        "!",
        "interface FastEthernet0/24",
        "!",
        "interface GigabitEthernet0/1",
        "!",
        "interface GigabitEthernet0/2",
        "!",
        "interface Vlan1",
        "no ip address",
        "shutdown",
        "!",
        "!",
        "!",
        "!",
        "line con 0",
        "!",
        "line vty 0 4",
        "login",
        "line vty 5 15",
        "login",
        "!",
        "!",
        "!",
        "!",
        "end"
      ]

def test_wrong_source_type():
    with pytest.raises(ValueError):
        InstructionParser.from_source("")
        InstructionParser.from_source("string")
        InstructionParser.from_source(1)
        InstructionParser.from_source({"a": 1})
        InstructionParser.from_source([1])
    InstructionParser.from_source([])
    InstructionParser.from_source(["string"])

def test_instruction_parser_router():
    x = InstructionParser.from_source(router_config_1)
    expected_parsed_instructions = ['hostname Router', 'ip cef',
                                    'no ipv6 cef', 'spanning-tree mode pvst',
                                    'interface GigabitEthernet0/0', 'no ip address',
                                    'duplex auto', 'speed auto', 'interface GigabitEthernet0/0.10',
                                    'encapsulation dot1Q 10', 'ip address 100.0.0.1 255.255.255.0',
                                    'interface GigabitEthernet0/0.20', 'encapsulation dot1Q 20',
                                    'ip address 200.0.0.2 255.255.255.0', 'interface GigabitEthernet0/1',
                                    'no ip address', 'duplex auto', 'speed auto', 'shutdown',
                                    'interface GigabitEthernet0/2', 'no ip address', 'duplex auto',
                                    'speed auto', 'shutdown', 'interface Vlan1', 'no ip address',
                                    'shutdown', 'ip classless', 'ip flow-export version 9', 'line con 0',
                                    'line aux 0', 'line vty 0 4', 'end']
    assert x == expected_parsed_instructions, f"Parsing {router_config_1} failed, got: {x}"

def test_instruction_parser_switch():
    x = InstructionParser.from_source(switch_config_1)
    expected_parsed_instructions = ['hostname Switch', 'spanning-tree mode pvst',
                                    'spanning-tree extend system-id', 'interface Vlan1',
                                    'no ip address', 'shutdown', 'line con 0',
                                    'line vty 0 4', 'line vty 5 15', 'end']
    assert x == expected_parsed_instructions, f"Parsing {switch_config_1} failed, got: {x}"
