version: 1
formatters:
  default:
    format: "[%(asctime)s] : [%(levelname)s] : %(message)s"
handlers:
  console:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  default:
    level: INFO
    handlers:
      - console
root:
  level: INFO
  handlers:
    - console